module.exports = {
  DYNAMODB_CONNECTIONS_TABLE: process.env.DYNAMODB_CONNECTIONS_TABLE,
  DYNAMODB_CONNECTIONS_TABLE_TYPE_GSI: process.env.DYNAMODB_CONNECTIONS_TABLE_TYPE_GSI,
  WEBSOCKET_API_ENDPOINT: (
    process.env.IS_OFFLINE
      ? process.env.LOCAL_WEBSOCKET_API_ENDPOINT
      : process.env.WEBSOCKET_API_ENDPOINT
  ),
};
